DEF CALCULATE_DISCOUNT(PRICE, DISCOUNT_PERCENT):
    # IF THE DISCOUNT IS 20% OR HIGHER, APPLY THE DISCOUNT
    IF DISCOUNT_PERCENT >= 20:
        DISCOUNT_AMOUNT = (DISCOUNT_PERCENT / 100) * PRICE
        FINAL_PRICE = PRICE - DISCOUNT_AMOUNT
        RETURN FINAL_PRICE
    ELSE:
        # OTHERWISE, RETURN THE ORIGINAL PRICE
        RETURN PRICE


# ASK THE USER FOR INPUT
PRICE = FLOAT(INPUT("ENTER THE ORIGINAL PRICE: "))
DISCOUNT_PERCENT = FLOAT(INPUT("ENTER THE DISCOUNT PERCENTAGE: "))

# CALL THE FUNCTION AND STORE THE RESULT
FINAL_PRICE = CALCULATE_DISCOUNT(PRICE, DISCOUNT_PERCENT)

# DISPLAY THE RESULT
IF DISCOUNT_PERCENT >= 20:
    PRINT(F"THE FINAL PRICE AFTER {DISCOUNT_PERCENT}% DISCOUNT IS: {FINAL_PRICE}")
ELSE:
    PRINT(F"NO DISCOUNT APPLIED. THE ORIGINAL PRICE IS: {PRICE}")
